Nested Function Definitions (Closures) and Recursion PR
ml4ai/skema pull request #240
Opened 2023-06-16 19:14 UTC by titomeister

This pull request adds changes to the Python2CAST and GroMEt generation steps of the Code2FN pipeline to support nested function definitions (a.k.a. closures). This PR also adds some changes that allow for support of basic recursive programs. The recursion support needs more discussion and iteration before it can fully handle every single case.

It also adds some preliminary test files for Closures and Recursion that do quick sanity checks for generation.

Resolves #190 
Resolves #199

2023-06-19 13:21 UTC, vincentraymond-ua reviewed
@titomeister - Overall looks good, and all relevant examples are generating Gromet!

 A few small recommendations:
- Remove commented print statements
- There are a few places where old code is being commented out. It could increase readability/reduce clutter to remove these comments, or if its a special case, adding a note alongside the comment for documentation. For example:
```python
# qualified_func_name = f"{'.'.join(node.func.con_scope)}.{node.func.name}_{node.invocation_index}"
qualified_func_name = f"{node.func.name}_id{node.func.id}"
```
- The testing script test_recursion.py defines a function test_closures, instead of test_recursion.

2023-06-19 20:43 UTC, myedibleenso requested changes
Thanks, @titomeister !  Just a bit of cleanup requested before we merge.

2023-06-19 20:43 UTC, myedibleenso commented on skema/program_analysis/CAST2FN/ann_cast/to_gromet_pass.py
> +        # print(var_environment)
let's remove these print statements

2023-06-19 20:43 UTC, myedibleenso commented on skema/program_analysis/CAST2FN/ann_cast/to_gromet_pass.py
> +        # identified_func_name = ".".join(node.func.con_scope)
This can also be removed.

2023-06-19 20:43 UTC, myedibleenso commented on skema/program_analysis/CAST2FN/ann_cast/to_gromet_pass.py
> +            # qualified_func_name = f"{'.'.join(node.func.con_scope)}.{node.func.name}_{node.invocation_index}"
Let's remove this as well.

2023-06-19 20:43 UTC, myedibleenso commented on skema/program_analysis/tests/test_recursion.py
> +def test_closures():
Let's rename this to `test_recursion()`

2023-06-19 20:43 UTC, myedibleenso commented on skema/program_analysis/tests/test_recursion.py
> +def test_closures():
These don't seem to test any aspects of the generated gromet.  Would be good to assert some of those expectations for each test case in a subsequent PR.

2023-06-19 20:43 UTC, myedibleenso commented on skema/program_analysis/tests/test_closures.py
> +def test_closures():
These don't seem to test any aspects of the generated gromet. Would be good to assert some of those expectations for each test case in a subsequent PR.

2023-06-23 23:50 UTC, myedibleenso approved these changes
Thanks, @titomeister !

2023-06-23 23:50 UTC, myedibleenso commented on skema/program_analysis/CAST2FN/ann_cast/to_gromet_pass.py
> +            schema_version="0.1.7",
Good catch!

2023-06-23 23:57 UTC, merged