Jastier/experimental testing
ml4ai/skema pull request #504
Opened 2023-09-26 15:59 UTC by jastier

Testing pipeline for MATLAB unit testing
Part of PR #501

2023-09-26 20:55 UTC, myedibleenso requested changes

2023-09-26 20:55 UTC, myedibleenso commented on skema/program_analysis/CAST/matlab/tests/.gitkeep
This file is no longer necessary, as the directory now contains files.

2023-09-26 21:09 UTC, jastier commented on .github/workflows/tests-and-docs.yml
> +    branches: [main, jastier/experimental_testing]
Done here:   [https://github.com/ml4ai/skema/pull/504/commits/bf5e9b4bca3d1ff5f4d2491bc4fa4aa36c1d62c8](https://github.com/ml4ai/skema/pull/504/commits/bf5e9b4bca3d1ff5f4d2491bc4fa4aa36c1d62c8)

2023-09-27 04:36 UTC, myedibleenso approved these changes
Thanks, @jastier !

2023-09-27 07:43 UTC, merged