Fixes/rewrite to some operators, additional comments and additional parsers
ml4ai/skema pull request #814
Opened 2024-02-21 23:58 UTC by deepsana

## Summary of Changes
Fixes/rewrite to some operators — integral, summation, gradients
Parser can handle:
- Derivative e.g. Dp/Dt, 
- Vector e.g. \vec{x}
### Related issues

Resolves ???

2024-02-22 04:35 UTC, adarshp requested changes
I've left a few comments.

2024-02-22 04:35 UTC, adarshp commented on skema/skema-rs/mathml/src/ast/operator.rs
> +pub struct DDerivative {
The `DDerivative` operator should be combined with the `Derivative` operator --- unless I am mistaken, their semantics are the same.

2024-02-22 04:35 UTC, adarshp commented on skema/skema-rs/mathml/src/ast/operator.rs
> +    pub lowlimit: Option<Box<MathExpression>>,
Can you change `lowlimit` to `lower_bound`

2024-02-22 04:35 UTC, adarshp commented on skema/skema-rs/mathml/src/ast/operator.rs
> +    pub uplimit: Option<Box<MathExpression>>,
Can you change `uplimit` to `upper_bound`

2024-02-22 04:35 UTC, adarshp commented on skema/skema-rs/mathml/src/ast/operator.rs
> +    pub lowlimit: Option<Box<MathExpression>>,
Change `lowlimit` to `lower_limit`

2024-02-22 04:35 UTC, adarshp commented on skema/skema-rs/mathml/src/ast/operator.rs
> +    pub uplimit: Option<Box<MathExpression>>,
Change `uplimit` to `upper_limit`

2024-02-22 04:35 UTC, adarshp commented on skema/skema-rs/mathml/src/ast/operator.rs
>      Hat,
What does the `Hat` operator mean? and why is there a separate `HatOp` operator?

2024-02-22 04:35 UTC, adarshp commented on skema/skema-rs/mathml/src/ast/operator.rs
> +    DownArrow(DownArrow),
What does the `DownArrow` operator mean?

2024-02-22 04:35 UTC, adarshp commented on skema/skema-rs/mathml/src/ast/operator.rs
>      SurfaceClosedIntNoIntVar,
`SurfaceClosedIntNoIntNoIntVar` should be combined with `SurfaceClosedInt`. Is there such a thing as an 'open' surface integral operator? If not, we may not need to specify 'closed' in the name of the operator.

2024-02-22 19:55 UTC, Free-Quarks commented on skema/skema-rs/skema/src/services/mathml.rs
>  };
Just noting that this is likely why the tests aren't passing. The `GeneralizedAMR` import got deleted for some reason.

2024-02-23 20:24 UTC, adarshp approved these changes

2024-02-27 17:16 UTC, closed without merging

2024-02-27 17:17 UTC, Free-Quarks commented
This got messed up with outdated commits and we reverted to another branch that targeted a clean commit